### ISSUE TITLE
Wrong rain unit

### ISSUE THREAD

**Issue by Cyrille56** [tguillaume02/Wmr500#1]
Hello,
Thanks for the tuto and the driver.
I still have a problem concerning the report and data sending to AWEKAS : weewx seems to believe that the rain unit is cm.
So I read 30 cm of rain in my reports (the WMR500 base show 3 mm).
Any idea ?
Thanks

**Comment by tguillaume02** [comment]
Hello,
I fixed the drivers, update it and check if it is good for you.
Unfortunately the old data cannot be updated, only the new ones will be good.
Best regards

**Comment by Cyrille56** [comment]
Hello,
I did the same correction in the weewx.conf : [StdCalibrate] rain = rain / 10
I think your solution is better.... I just wait rain too see...
No problem for the old data, I'm still in test.
Thanks
